/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess;

import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Kero
 */
public class GameFrame extends javax.swing.JFrame implements Serializable{

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EasyBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        NormalBtn = new javax.swing.JButton();
        HardBtn = new javax.swing.JButton();
        NewGameBtn = new javax.swing.JButton();
        CreditsBtn = new javax.swing.JButton();
        HowToPlayBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        LoadBtn = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(619, 350));
        setPreferredSize(new java.awt.Dimension(600, 419));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 419));
        getContentPane().setLayout(null);

        EasyBtn.setBackground(new java.awt.Color(153, 153, 153));
        EasyBtn.setText("Easy");
        EasyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EasyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EasyBtn);
        EasyBtn.setBounds(50, 60, 100, 26);
        EasyBtn.setVisible(false);

        BackBtn.setBackground(new java.awt.Color(153, 153, 153));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(50, 210, 100, 26);
        BackBtn.setVisible(false);

        NormalBtn.setBackground(new java.awt.Color(153, 153, 153));
        NormalBtn.setText("Normal");
        NormalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalBtnActionPerformed(evt);
            }
        });
        getContentPane().add(NormalBtn);
        NormalBtn.setBounds(50, 110, 100, 26);
        NormalBtn.setVisible(false);

        HardBtn.setBackground(new java.awt.Color(153, 153, 153));
        HardBtn.setText("Hard");
        HardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HardBtn);
        HardBtn.setBounds(50, 160, 100, 26);
        HardBtn.setVisible(false);

        NewGameBtn.setBackground(new java.awt.Color(153, 153, 153));
        NewGameBtn.setText("New Game");
        NewGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameBtnActionPerformed(evt);
            }
        });
        getContentPane().add(NewGameBtn);
        NewGameBtn.setBounds(50, 110, 100, 26);

        CreditsBtn.setBackground(new java.awt.Color(153, 153, 153));
        CreditsBtn.setText("Credits");
        getContentPane().add(CreditsBtn);
        CreditsBtn.setBounds(50, 160, 100, 26);

        HowToPlayBtn.setBackground(new java.awt.Color(153, 153, 153));
        HowToPlayBtn.setText("How To Play");
        getContentPane().add(HowToPlayBtn);
        HowToPlayBtn.setBounds(50, 210, 100, 26);

        ExitBtn.setBackground(new java.awt.Color(153, 153, 153));
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBtn);
        ExitBtn.setBounds(50, 260, 103, 26);

        LoadBtn.setBackground(new java.awt.Color(153, 153, 153));
        LoadBtn.setText("Load Game");
        LoadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoadBtn);
        LoadBtn.setBounds(500, 40, 100, 26);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chess/imgs/chess-king.jpg"))); // NOI18N
        Background.setName(""); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, -20, 630, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void NewGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameBtnActionPerformed
        try {
            // TODO add your handling code here:
            EasyBtn.setVisible(true);
            NormalBtn.setVisible(true);
            HardBtn.setVisible(true);
            BackBtn.setVisible(true);
            //new GameBoard().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GameFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //this.setVisible(false);
    }//GEN-LAST:event_NewGameBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
            EasyBtn.setVisible(false);
            NormalBtn.setVisible(false);
            HardBtn.setVisible(false);
            BackBtn.setVisible(false);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void EasyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EasyBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new GameBoard(1,false,new ArrayList<Object>()).setVisible(true);
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(GameFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EasyBtnActionPerformed

    private void NormalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new GameBoard(3,false,new ArrayList<Object>()).setVisible(true);
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(GameFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
               
    }//GEN-LAST:event_NormalBtnActionPerformed

    private void HardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new GameBoard(1,false,new ArrayList<Object>()).setVisible(true);
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(GameFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_HardBtnActionPerformed

    private void LoadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setAcceptAllFileFilterUsed(false);
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Willson", "willson"));
        

                int result= fc.showOpenDialog(this);
            if(result==JFileChooser.APPROVE_OPTION)
            {
                ArrayList<Object> data = new ArrayList<>();
                try {
                    FileInputStream fileIn = new FileInputStream(fc.getSelectedFile().getAbsolutePath());
                    ObjectInputStream in = new ObjectInputStream(fileIn);
                    data = (ArrayList<Object>) in.readObject();
                    in.close();
                    fileIn.close();
                    
                    new GameBoard((int)data.get(0),true,data ).setVisible(true);
                    this.setVisible(false);
                    
                } catch (Exception e) {
                    System.out.println("errorrrrr");
                }
            }
        
//        if (selectedFile != null) {
//            System.out.println(selectedFile.getAbsolutePath());
//        }
    }//GEN-LAST:event_LoadBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                String bip = "el3ab.mp3";
                new GameFrame().setVisible(true);
//                Media hit = new Media(new File(bip).toURI().toString());
//                MediaPlayer mediaPlayer = new MediaPlayer(hit);
//                mediaPlayer.play();
//                AudioInputStream audioIn;
//                try {
//                    audioIn = AudioSystem.getAudioInputStream(getClass().getResource("/chess/imgs/el3ab.wav"));
//                    Clip clip = AudioSystem.getClip();
//                clip.open(audioIn);
//                clip.loop(Clip.LOOP_CONTINUOUSLY);
//                clip.start();
//                } catch (UnsupportedAudioFileException ex) {
//                    Logger.getLogger(GameFrame.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (IOException ex) {
//                    Logger.getLogger(GameFrame.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (LineUnavailableException ex) {
//                    Logger.getLogger(GameFrame.class.getName()).log(Level.SEVERE, null, ex);
//                }
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Background;
    private javax.swing.JButton CreditsBtn;
    private javax.swing.JButton EasyBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton HardBtn;
    private javax.swing.JButton HowToPlayBtn;
    private javax.swing.JButton LoadBtn;
    private javax.swing.JButton NewGameBtn;
    private javax.swing.JButton NormalBtn;
    // End of variables declaration//GEN-END:variables
}
