/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess;

import javax.swing.JFrame;

/**
 *
 * @author Kero
 */
public class GameFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewGameBtn = new javax.swing.JButton();
        CreditsBtn = new javax.swing.JButton();
        HowToPlayBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(619, 350));
        setPreferredSize(new java.awt.Dimension(600, 435));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 419));
        getContentPane().setLayout(null);

        NewGameBtn.setBackground(new java.awt.Color(153, 153, 153));
        NewGameBtn.setText("New Game");
        NewGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameBtnActionPerformed(evt);
            }
        });
        getContentPane().add(NewGameBtn);
        NewGameBtn.setBounds(50, 110, 103, 29);

        CreditsBtn.setBackground(new java.awt.Color(153, 153, 153));
        CreditsBtn.setText("Credits");
        getContentPane().add(CreditsBtn);
        CreditsBtn.setBounds(50, 160, 103, 29);

        HowToPlayBtn.setBackground(new java.awt.Color(153, 153, 153));
        HowToPlayBtn.setText("How To Play");
        getContentPane().add(HowToPlayBtn);
        HowToPlayBtn.setBounds(50, 210, 100, 29);

        ExitBtn.setBackground(new java.awt.Color(153, 153, 153));
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBtn);
        ExitBtn.setBounds(50, 260, 103, 29);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chess/imgs/chess-king.jpg"))); // NOI18N
        Background.setName(""); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, -20, 630, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void NewGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameBtnActionPerformed
        // TODO add your handling code here:
        new GameBoard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NewGameBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton CreditsBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton HowToPlayBtn;
    private javax.swing.JButton NewGameBtn;
    // End of variables declaration//GEN-END:variables
}
